add_newline = false

[character] # The name of the module we are configuring is "character"
format = "  "


[username]
style_user = "green bold"
style_root = "black bold"
format = "[$user]($style) on "
disabled = false
show_always = true

[hostname]
disabled = false
ssh_only = false
format = "[$hostname](bold red) "

[rust]
# format = "using [⚙️ $version](red bold)"


[git_metrics]
disabled = false
