add_newline = false

[character] # The name of the module we are configuring is "character"
format = "➜ "

[hostname]
disabled = false
ssh_only = false
format = "koho@[$hostname](bold red) "


[git_metrics]
disabled = false
