require("signal.volume")
require("signal.brightness")
require("signal.ram")
require("signal.cpu")
require("signal.temp")
require("signal.disk")
require("signal.batterystatus")
require("signal.wifistatus")
require("signal.bluetooth")

